import {AppConstants} from "../../../../../../../app.utility";

export function MappedPendingOrder(data: any): any {
    return {
        account: data.account,
        accrudeProfit: data.accrudeProfit,
        actual_broker_code: data.actual_broker_code || "",
        actual_client_code: data.actual_client_code || "",
        actual_settlement_amount: data.actual_settlement_amount || 0,
        actual_volume: data.actual_volume || 0,
        broker: data.participant,
        contract_id: data.contract_id || "0",
        contract_initial_date: new Date().toISOString(),
        counter_broker_code: data.counter_broker_code || "",
        counter_client_code: data.counter_client_code || "",
        counter_order_no: data.counter_order_no || null,
        counter_user_id: data.counter_user_id || 0,
        counter_username: data.counter_username || "",
        custodian: data.custodian || "",
        dirtyPrice: data.dirtyPrice || 0,
        disclosedVolume: data.disclosedVolume || 0,
        discQuantity: data.discQuantity || 0,
        exchange: data.exchange,
        expiryDate: data.expiryDate || "",
        gtd: data.gtd || new Date().toISOString(),
        is_negotiated: data.is_negotiated || false,
        lang: data.lang || "en",
        market: data.market,
        marketValue: data.marketValue || 0,
        negotiated_order_state: data.negotiated_order_state || "",
        negotiated_order_status: data.negotiated_order_status || "",
        nominalValue: data.nominalValue || 0,
        order_no: "",
        order_state: data.order_state || "",
        participant: data.participant,
        price: data.price || "0",
        price_: data.price_ || 0,
        pricingMechanism: data.pricingMechanism || 0,
        qualifier: data.qualifier,
        ref_no: data.ref_no || "",
        repo_haircut: data.repo_haircut || "",
        repo_haircut_: data.repo_haircut_ || 0,
        repo_leg: data.repo_leg || 1,
        repo_type: data.repo_type,
        repurchase_price: data.repurchase_price || "",
        repurchase_price_: data.repurchase_price_ || 0,
        repurchase_rate: data.repurchase_rate || "",
        repurchase_rate_: data.repurchase_rate_ || 0,
        sellPrice: data.sellPrice || 0,
        sender_username: data.sender_username || "",
        settlementValue: data.settlementValue || 0,
        side: data.side,
        state_time: data.state_time || null,
        sVolume: data.sVolume || "",
        symbol: data.symbol || "",
        symbolMktExch: `${data.symbol}(${data.market}/${data.exchange})`,
        symbolType: data.symbolType || 0,
        terminationDate: data.terminationDate || null,
        tifOption: data.tifOption,
        triggerPrice: data.triggerPrice || "0",
        triggerPrice_: data.triggerPrice_ || 0,
        type: data.type,
        type_: data.type_,
        username: data.username,
        value: data.value || 0,
        volume: data.volume || 0,
        yield: data.yield || 0,
    };
}
