import {AppConstants} from "../../../../../../app.utility";

export function MappedNegOrder(data: any): any {
    return {
        account: data.account,
        accrudeProfit: data.accrudeProfit,
        actual_broker_code: data.actual_broker_code || "",
        actual_client_code: data.actual_client_code || "",
        actual_settlement_amount: Number(data.actual_settlement_amount),
        actual_volume: data.actual_volume,
        broker: data.participant,
        contract_id: data.contract_id,
        contract_initial_date: new Date().toISOString(),
        counter_broker_code: data.counter_broker_code,
        counter_client_code: data.counter_client_code || "",
        counter_order_no: data.counter_order_no,
        counter_user_id: 0,
        counter_username: "",
        custodian: data.custodian || "",
        dirtyPrice: data.dirtyPrice,
        disclosedVolume: data.disclosedVolume,
        discQuantity: data.discQuantity || 0,
        exchange: data.exchange,
        expiryDate: data.expiryDate || "",
        gtd: new Date().toISOString(),
        is_negotiated: data.is_negotiated,
        lang: data.lang || "en",
        market: data.market,
        marketValue: data.marketValue,
        negotiated_order_state: data.negotiated_order_state,
        negotiated_order_status: data.negotiated_order_status,
        nominalValue: data.nominalValue || 0,
        order_no: "",
        order_state: data.order_state || "",
        participant: data.participant,
        price: data.price,
        price_: data.price_,
        pricingMechanism: data.pricingMechanism,
        qualifier: data.qualifier,
        ref_no: data.ref_no || "",
        repo_haircut: "",
        repo_haircut_: data.repo_haircut_,
        repo_leg: data.repo_leg,
        repo_type: data.repo_type,
        repurchase_price: "",
        repurchase_price_: data.repurchase_price_,
        repurchase_rate: data.repurchase_rate || "",
        repurchase_rate_: 0,
        sellPrice: data.sellPrice || 0,
        sender_username: data.sender_username,
        settlementValue: data.settlementValue || 0,
        side: data.side,
        state_time: data.state_time || null,
        sVolume: data.sVolume || "",
        symbol: data.symbol,
        symbolMktExch: `${data.symbol}(${data.market}/${data.exchange})`,
        symbolType: data.symbolType || 0,
        terminationDate: data.terminationDate || null,
        tifOption: data.tifOption,
        triggerPrice: data.triggerPrice || "0",
        triggerPrice_: data.triggerPrice_,
        type: data.type,
        type_: data.type_ || data.type,
        username: data.username,
        value: data.value,
        volume: data.volume,
        yield: data.yield,
    };
}
